export { default as imgOne } from './images/img01.jpg'
export { default as imgTwo } from './images/img02.jpg'
export { default as imgThree } from './images/img03.jpg'
export { default as imgFour } from './images/img04.jpg'
export { default as imgFive } from './images/img05.jpg'
export { default as imgSix } from './images/img06.jpg'
export { default as prizeBg } from './images/prizebg.jpg'